/**
 * LedgerFlow CRM — Buy New Services Catalog
 * Main categories and services offered by the accounting firm to clients.
 */
window.SERVICE_CATALOG = [
    {
        id: 'business',
        name: 'Business',
        icon: 'fa-building',
        color: 'emerald',
        services: [
            'Proprietorship Registration',
            'Partnership Registration',
            'Nidhi Company',
            'Private Limited Company',
            'Public Limited Company',
            'Section 8 Company',
            'Producer Company',
            'One Person Company',
            'Trust Registration',
            'Limited Liability Partnership',
            'Proprietor to LLP',
            'Proprietor to Pvt Ltd',
            'Partnership to LLP',
            'Partnership to Pvt Ltd',
            'Proprietor to OPC',
            'LLP to Pvt Ltd',
            'MCA Name Approval'
        ]
    },
    {
        id: 'certifications',
        name: 'Certifications',
        icon: 'fa-certificate',
        color: 'blue',
        services: [
            'Fire Licence',
            'DSC Registration',
            'Gumasta Registration',
            'PF Registration',
            'ESI Registration',
            'ICEGATE Registration',
            'PT Registration',
            'RERA Registration',
            'Only 80G Registration',
            'HIP FIR',
            'GeM Registration',
            'Udyam Registration',
            'Only 12A Registration',
            'GST Registration',
            'FCRA Registration',
            '12A and 80G Registration',
            'ISO Registration',
            'FSSAI Registration',
            'Import Export Registration',
            'ZED Certification',
            'Darpan Registration',
            'Tax Exemption Certificate',
            'BIS Registration',
            'Barcode Registration',
            'Startup India Registration'
        ]
    },
    {
        id: 'compliance',
        name: 'Compliance',
        icon: 'fa-clipboard-check',
        color: 'purple',
        services: [
            'Compliance',
            'ADT-1 Filing',
            'DPT-3 Filing',
            'Business Plan',
            'AOA Amendment',
            'MOA Amendment',
            'Share Transfer',
            'Demat of Shares',
            'Remove Director',
            'Director Change',
            'LLP Compliance',
            'OPC Compliance',
            'Winding Up – LLP',
            'DIN eKYC Filing',
            'DIN Reactivation',
            'PF Return Filing',
            'PT Return Filing',
            'Winding Up Company',
            'Company Compliance',
            'ESI Return Filing',
            'FLA Return Filing',
            'LLP Form 11 Filing',
            'Dormant Status Filing',
            'Name Change Company',
            'Partnership Compliance',
            'Registered Office Change',
            'Proprietorship Compliance',
            'Authorized Capital Increase'
        ]
    },
    {
        id: 'taxation',
        name: 'Taxation',
        icon: 'fa-landmark',
        color: 'amber',
        services: [
            'Composition Return',
            'GST Cancellation',
            'GST Return Filing',
            'GST Nil Return',
            'ITR-1 (Only Salary)',
            'ITR-2 (Salary & Other)',
            'ITR-3 Return Filing',
            'ITR-4 Return Filing',
            'ITR-5 Return Filing',
            'ITR-6 Return Filing',
            'ITR-7 Return Filing'
        ]
    },
    {
        id: 'exports',
        name: 'Exports',
        icon: 'fa-globe',
        color: 'cyan',
        services: [
            'Council for Leather Exports',
            'Handloom Export Promotion Council',
            'Ayush Export Promotion Council',
            'Plastics Export Promotion Council',
            'Services Export Promotion Council',
            'Cotton Textiles EPC',
            'Wool Industry EPC',
            'Electronics & Software EPC',
            'Gem & Jewellery EPC',
            'Cashew Export Promotion Council',
            'Wool & Woollens EPC',
            'Sports Goods & Toys EPC',
            'Export Promotion Council for Handicrafts',
            'Medical Devices EPC',
            'Technical Textiles EPC',
            'RCMC Registration',
            'APEDA Registration',
            'FIEO',
            'Indian Silk Export Promotion Council',
            'Oilseeds & Produce EPC',
            'Shellac & Forest Products EPC',
            'Powerloom Development & EPC',
            'Project Exports Promotion Council',
            'Pharmaceuticals EPC',
            'Export Promotion Council for EOUS & SEZ',
            'Marine Products Export Development Authority',
            'Handicrafts, Jammu and Kashmir',
            'EEPC INDIA',
            'Telecom Equipment & Services EPC',
            'Chemicals & Dyes EPC',
            'Jute Products EPC',
            'Mobile & Electronic Devices EPC',
            'Tea Board',
            'Coir Board',
            'Coffee Board',
            'Rubber Board',
            'Spices Board',
            'Tobacco Board',
            'CAPEXIL',
            'Coconut Development Board',
            'Carpet Export Promotion Council',
            'Apparel Export Promotion Council'
        ]
    },
    {
        id: 'trademark',
        name: 'Trademark',
        icon: 'fa-trademark',
        color: 'rose',
        services: [
            'Trademark Registration',
            'Trademark Objection',
            'Trademark Certificate',
            'Trademark Opposition',
            'Trademark Hearing',
            'Trademark Rectification',
            'TM Infringement Notice',
            'Trademark Renewal',
            'Trademark Transfer',
            'Expedited Trademark Registration',
            'Design Registration',
            'Design Objection',
            'Copyright Registration',
            'Copyright Objection',
            'Patent Registration'
        ]
    }
];

window.getServiceById = function(categoryId, serviceName) {
    const cat = window.SERVICE_CATALOG.find(c => c.id === categoryId);
    if (!cat) return null;
    if (!serviceName) return cat;
    return cat.services.includes(serviceName) ? { category: cat, serviceName } : null;
};